const songs = [
    [
        {
            songName: "Ain't No Mountain High Enough - Marvin Gaye, Tammi Terrell",
            songSrc: "assets/music/60/cut/Ain't No Mountain High Enough - Marvin Gaye, Tammi Terrell.mp3",
            songImg: "assets/img/60/Ain't No Mountain High Enough - Marvin Gaye, Tammi Terrell.jpg",
            en: `The song was written by Ashford and Simpson prior to joining Motown. British soul singer Dusty Springfield wanted to record the song but the duo declined, hoping it would give them access to the Detroit-based label. As Valerie Simpson later recalled, "We played that song for her (Springfield) but wouldn't give it to her, because we wanted to hold that back. We felt like that could be our entry to Motown. Nick called it the 'golden egg'.`,
            ru: `Песня была написана Эшфордом и Симпсоном до прихода в Motown. Британский соул-певец Дасти Спрингфилд хотел записать эту песню, но дуэт отказался, надеясь, что это даст им доступ к детройтскому лейблу. Как позже вспоминала Валери Симпсон: «Мы сыграли эту песню для нее (Спрингфилд), но не дали ее ей, потому что хотели сдержать это. Мы чувствовали, что это может стать нашим входом в Motown. Ник назвал ее «золотой». яйцо'.`,
        },
        {
            songName: "All I Have To Do Is Dream - The Everly Brothers",
            songSrc: "assets/music/60/cut/All I Have To Do Is Dream - The Everly Brothers.mp3",
            songImg: "assets/img/60/All I Have To Do Is Dream - The Everly Brothers.jpg",
            en: `"All I Have to Do Is Dream" is a song made famous by the Everly Brothers, written by Boudleaux Bryant of the husband-and-wife songwriting team Felice and Boudleaux Bryant, and published in 1958. The song is ranked No. 141 on the Rolling Stone magazine's list of The 500 Greatest Songs of All Time.`,
            ru: `«All I Have to Do Is Dream» (рус. Всё, что мне остаётся, это мечтать) — популярная песня американского дуэта The Everly Brothers, записанная в 1958 году. Под номером 142 входит в список 500 величайших песен всех времён по версии журнала Rolling Stone.`,
        }
        ,
        {
            songName: "California Dreamin - The Mamas, The Papas",
            songSrc: "assets/music/60/cut/California Dreamin - The Mamas, The Papas.mp3",
            songImg: "assets/img/60/California Dreamin - The Mamas, The Papas.jpg",
            en: `"California Dreamin'" is a song written by John Phillips and Michelle Phillips and first recorded by Barry McGuire. The best-known version is by the Mamas & the Papas, who sang backup on the original version and released it as a single in 1965. The lyrics express the narrator's longing for the warmth of Los Angeles during a cold winter in New York City.`,
            ru: `«California Dreamin’» (с англ. — «Мечтая о Калифорнии») — песня The Mamas & the Papas, выпущенная в 1965 году. Текст песни выражает тоску автора по теплу Лос-Анджелеса во время холодной зимы в Нью-Йорке.`,
        },
        {
            songName: "Can't Help Falling In Love - Elvis Presley",
            songSrc: "assets/music/60/cut/Can't Help Falling In Love - Elvis Presley.mp3",
            songImg: "assets/img/60/Can't Help Falling In Love - Elvis Presley.jpg",
            en: `"Can't Help Falling in Love" is a song recorded by American singer Elvis Presley for the album Blue Hawaii (1961). The melody is based on "Plaisir d'amour", a popular French love song composed in 1784 by Jean-Paul-Égide Martini. The song was initially written from the perspective of a woman as "Can't Help Falling in Love with Him", which explains the first and third line ending on "in" and "sin" rather than words rhyming with "you".`,
            ru: `«Can’t Help Falling in Love» — песня, записанная американским певцом Элвисом Пресли для альбома Blue Hawaii (1961). Мелодия основана на популярной французской любовной песне «Plaisir d'amour», сочиненной в 1784 году Жан-Полем-Эгидом Мартини. Изначально песня была написана с точки зрения женщины как «Не могу не влюбиться в него», что объясняет первую и третью строчки, оканчивающиеся на «в» и «грех», а не слова, рифмующиеся со словом «ты».`,
        }
        ,
        {
            songName: "Hit the Road Jack - Ray Charles",
            songSrc: "assets/music/60/cut/Hit the Road Jack - Ray Charles.mp3",
            songImg: "assets/img/60/Hit the Road Jack - Ray Charles.jpg",
            en: `"Hit the Road Jack" is a song written by the rhythm and blues singer Percy Mayfield and recorded by Ray Charles. The song was a US number 1 hit in 1961, and won a Grammy award for Best Rhythm and Blues Recording, becoming one of Charles' signature songs.`,
            ru: `Hit The Road Jack (с англ. — «Проваливай, Джек») — песня построена на диалоге женщины, которая упрекает своего мужчину в том, что у него за душой ни гроша, и требует, чтобы он собрал свои вещи и покинул её дом, и ответом мужчины, который обвиняет женщину в сварливости и обещает наверстать упущенное.`,
        }
        ,
        {
            songName: "I'm a Beliver - The Monkees",
            songSrc: "assets/music/60/cut/I'm a Beliver - The Monkees.mp3",
            songImg: "assets/img/60/I'm a Beliver - The Monkees.jpg",
            en: `"I'm a Believer" is a song written by Neil Diamond and recorded by the Monkees in 1966 with the lead vocals by Micky Dolenz. The single, produced by Jeff Barry, hit the number-one spot on the U.S. Billboard Hot 100 chart for the week ending December 31, 1966, and remained there for seven weeks, becoming the last No. 1 hit of 1966 and the biggest-selling single for all of 1967. Billboard ranked the record as the No. 5 song for 1967.`,
            ru: `«I'm a Believer» (с англ. — «Я верю») ― песня заняла 1-е место в американском чарте Billboard Hot 100 за неделю, и оставалась там в течение 7 недель, став последним хитом 1966 года и самым продаваемым синглом 1967 года. Журнал Billboard поместил песню на 5-е место в списке лучших песен за 1967 год. Благодаря 1 051 280 предварительных заказов она стала золотой в течение двух дней после выпуска. Это один из сорок`,
        }
        ,
        {
            songName: "It's My Party - Lesley Gore",
            songSrc: "assets/music/60/cut/It's My Party - Lesley Gore.mp3",
            songImg: "assets/img/60/It's My Party - Lesley Gore.jpg",
            en: `"It's My Party" is a song by American singer-songwriter Lesley Gore from her debut studio album I'll Cry If I Want To (1963). It was released as the lead single from the album on April 5, 1963, by Mercury Records. The song was collectively written by Herb Wiener, John Gluck Jr., and Wally Gold, whilst production was helmed by Quincy Jones.`,
            ru: `«It’s My Party» — песня американской певицы и автора песен Лесли Гор из её дебютного студийного альбома «I’ll Cry If I Want To» (1963). Он был выпущен как главный сингл с альбома 5 апреля 1963 года на лейбле Mercury Records. Песня была написана совместно Хербом Винером, Джоном Глаком-младшим и Уолли Голдом, а производством руководил Куинси Джонс.`,
        },
        {
            songName: "Jonny B. Goode - Chuck Berry",
            songSrc: "assets/music/60/cut/Jonny B. Goode - Chuck Berry.mp3",
            songImg: "assets/img/60/Jonny B. Goode - Chuck Berry.jpg",
            en: `"Johnny B. Goode" is considered one of the most recognizable songs in the history of popular music. Credited as "the first rock & roll hit about rock & roll stardom", it has been recorded by many other artists and has received several honors and accolades, including being ranked seventh on Rolling Stone's list of the "500 Greatest Songs of All Time" and included as one of the 27 songs on the Voyager Golden Record, a collection of music, images, and sounds designed to serve as a record of humanity.`,
            ru: `«Johnny B. Goode» («Джонни Би Гуд») — песня занимает 1 место в рейтинге 100 величайших гитарных песен всех времён по версии журнала Rolling Stone. В характерной для Берри манере песня представляет собой небольшой рассказ о неграмотном, но талантливом деревенском пареньке, который очаровал всех своей игрой на гитаре. Название песни — игра слов: «Johnny B. Goode» выглядит как обычное имя и фамилия, при этом звучит по-английски как Johnny be good («Джонни, будь добр» или «Джонни, будь умницей»), и кроме того, намекает на автобиографические моменты: Чак Берри родился на Гуд-авеню (Goode Avenue) в Сент-Луисе.`,
        },
        {
            songName: "Oh, Pretty Woman - Roy Orbison",
            songSrc: "assets/music/60/cut/Oh, Pretty Woman - Roy Orbison.mp3",
            songImg: "assets/img/60/Oh, Pretty Woman - Roy Orbison.jpg",
            en: `"Oh, Pretty Woman" or simply "Pretty Woman"  - was released as a single in August 1964 on Monument Records and spent three weeks at number one on the Billboard Hot 100 from September 26, 1964, the second and final single by Orbison to top the US charts.  The LP version with the intended lyric: "come with me baby" was changed for the single to "come to me baby" as the former was considered too risque. `,
            ru: `«Oh, Pretty Woman» или просто «Pretty Woman». Он был выпущен как сингл в августе 1964 года на лейбле Monument Records и три недели занимал первое место в Billboard Hot 100 с 26 сентября 1964 года. возглавить чарты США. Версия LP с предполагаемой лирикой: «Пойдем со мной, детка» была изменена на сингл на «Иди ко мне, детка», поскольку первое было сочтено слишком рискованным.`,
        },
    ],
    [
        {
            songName: `D.I.S.C.O. - Ottawan`,
            songSrc: `assets/music/70/cut/D.I.S.C.O. - Ottawan.mp3`,
            songImg: `assets/img/70/D.I.S.C.O. - Ottawan.jpg`,
            en: `"D.I.S.C.O." is a song by the French band Ottawan, written by Daniel Vangarde and Jean Kluger and produced by Daniel Vangarde. Ottawan originally recorded it in French. It was first released in 1979 and reached number two in the UK Singles Chart the following year. The song's name is an acronym and comes from the lyrics in its chorus, in which a woman is described as "D.I.S.C.O.". In other words, each letter of the word standing for a certain quality, except "O", which simply leads to singing "oh-oh-oh" ("She is D, delirious / She is I, incredible / She is S, superficial / She is C, complicated / She is oh-oh-oh").`,
            ru: `«D.I.S.C.O.» — песня французской группы Ottawan в стиле диско, написанная Жаном Клюгером и Даниэлем Вангаром (отцом Т. Бангальтера из Daft Punk). Композиция, существующая в двух (англоязычной и франкоязычной) версиях, была записана в конце 1979 года и стала одним из наиболее успешных релизов группы. В тексте припева обыгрывается название песни: каждая буква названия соответствует какому-нибудь качеству («She is disco // She is D delirious // She is I incredible // She is S superficial // She is C complicated // She is O oh, oh, oh»).`,
        }, 
        {
            songName: `Daddy Cool - Boney M`,
            songSrc: `assets/music/70/cut/Daddy Cool - Boney M.mp3`,
            songImg: `assets/img/70/Daddy Cool - Boney M.jpg`,
            en: `"Daddy Cool" is a song recorded by Boney M. and included on their debut album Take the Heat off Me. It was a 1976 hit and a staple of disco music and became Boney M.'s first hit in the United Kingdom. The second Boney M. single, it was released in 1976 and made no major impact at first. After a spectacular performance on the Musikladen TV show in September that year, the single became a hit, topping most European charts. `,
            ru: `«Daddy Cool» — песня, записанная Boney M. и вошедшая в их дебютный альбом Take the Heat off Me. Это был хит 1976 года, основной элемент диско-музыки и первый хит Boney M. в Соединенном Королевстве. Второй сингл Boney M. был выпущен в 1976 году и поначалу не произвел большого впечатления. После эффектного выступления на телешоу Musikladen в сентябре того же года сингл стал хитом, возглавив большинство европейских чартов.`,
        }, 
        {
            songName: `Dancing Queen - ABBA`,
            songSrc: `assets/music/70/cut/Dancing Queen - ABBA.mp3`,
            songImg: `assets/img/70/Dancing Queen - ABBA.jpg`,
            en: `Dancing Queen" is a Europop and disco song by the Swedish group ABBA, released as the lead single from their fourth studio album, Arrival (1976). It was written by Benny Andersson, Björn Ulvaeus and Stig Anderson. Andersson and Ulvaeus also produced the song. "Dancing Queen" was released as a single in Sweden on 15 August 1976, followed by a UK release and the rest of Europe a few days later. It was a worldwide hit.`,
            ru: `«Dancing Queen» (с англ.   — «Королева танцев», «Танцующая королева») — песня шведской группы ABBA, релиз которой следует за выпуском наблюдаемого хита «Fernando». Ее обычно считают одной из лучших композиций 1970-х годов, а также визитной карточкой группы АВВА.`,
        }, 
        {
            songName: `Gimme! Gimme! Gimme! - ABBA`,
            songSrc: `assets/music/70/cut/Gimme! Gimme! Gimme! - ABBA.mp3`,
            songImg: `assets/img/70/Gimme! Gimme! Gimme! - ABBA.jpg`,
            en: `"Gimme! Gimme! Gimme! (A Man After Midnight)" is a song by Swedish band ABBA. It was recorded in August 1979 in order to help promote their North American and European tour of that year, and was released on ABBA's Greatest Hits Vol. 2 album as the brand new track. "Gimme! Gimme! Gimme! (A Man After Midnight)" was written and composed by Benny Andersson and Björn Ulvaeus, with the lead vocal sung by Agnetha Fältskog. Fältskog, as the narrator, weaves the image of a lonely woman who longs for a romantic relationship and views her loneliness as a forbidding darkness of night, even drawing parallels to how the happy endings of movie stars are so different from her own existence.`,
            ru: `«Gimme! Gimme! Gimme! (A Man After Midnight)» (первоначальное название: «Been and Gone and Done It») — один из наиболее значимых диско-хитов шведской группы ABBA. Первоначально ABBA записывала другую песню, «Rubber Ball Man», однако им показалось, что песня «Gimme! Gimme! Gimme!» с её диско-ритмами будет лучшим выбором, и поэтому «Rubber Ball Man» осталась лишь демоверсией.`,
        }, 
        {
            songName: `Got To Be Real - Cheryl Lynn`,
            songSrc: `assets/music/70/cut/Got To Be Real - Cheryl Lynn.mp3`,
            songImg: `assets/img/70/Got To Be Real - Cheryl Lynn.jpg`,
            en: `"Got to Be Real" is a song by American singer Cheryl Lynn from her 1978 self-titled debut studio album. In the United States, "Got to Be Real" hit number 12 on the Billboard Hot 100 and hit number one on the Hot Soul Singles chart in early 1979. Along with the album tracks "Star Love" and "You Saved My Day", "Got to Be Real" peaked at number eleven on the National Disco Action Top 40 chart.`,
            ru: `«Got to Be Real» — песня американской певицы Шерил Линн из её одноименного дебютного студийного альбома 1978 года. В Соединенных Штатах "Got to Be Real" занял 12-е место в Billboard Hot 100 и первое место в чарте Hot Soul Singles в начале 1979 года. Наряду с треками из альбома "Star Love" и "You Saved My Day", "Got to Be Real" занял одиннадцатую позицию в чарте National Disco Action Top 40.`,
        }, 
        {
            songName: `Hotel California - Eagles`,
            songSrc: `assets/music/70/cut/Hotel California - Eagles.mp3`,
            songImg: `assets/img/70/Hotel California - Eagles.jpg`,
            en: `"Hotel California" is the title track from the Eagles' album of the same name and was released as a single in February 1977. Since its release, "Hotel California" has been covered by many artists. Julia Phillips proposed adapting the song into a film, but the members of the Eagles disliked the idea and it never came to fruition. Commercially, "Hotel California" reached the number one position on the Billboard Hot 100 and reached the top ten of several international charts.
            "Hotel California" is the title track from the Eagles' album of the same name and was released as a single in February 1977. Since its release, "Hotel California" has been covered by many artists. Julia Phillips proposed adapting the song into a film, but the members of the Eagles disliked the idea and it never came to fruition. Commercially, "Hotel California" reached the number one position on the Billboard Hot 100 and reached the top ten of several international charts.`,
            ru: `«Hotel California» (Отель «Калифорния») — песня описывает «гостиницу, которую нельзя покинуть никогда». Песня напоминает рассказ утомлённого путешественника, пойманного в ловушку в кошмарной гостинице, которая сначала казалась весьма привлекательной.`,
        }, 
        {
            songName: `Love hurts Lyrics - Nazareth`,
            songSrc: `assets/music/70/cut/Love hurts Lyrics - Nazareth.mp3`,
            songImg: `assets/img/70/Love hurts Lyrics - Nazareth.jpg`,
            en: `The hard rock group Nazareth took in 1974 sweet melody and quite corny lyrics by the then (1960) very popular Everly Brothers (Their version) and converted it to a soulful, hard driving rock ballade.
            It reached the Top 10 in the US and gained a respectable place on rock stations playlists.`,
            ru: `Хард-рок-группа Nazareth взяла в 1974 году сладкую мелодию и довольно банальную лирику очень популярных тогда (1960) Everly Brothers (их версия) и превратила их в душевную, жесткую рок-балладу.
            Он вошел в десятку лучших в США и занял почетное место в плейлистах рок-станций.`,
        }, 
        {
            songName: `One way ticket - Eruption`,
            songSrc: `assets/music/70/cut/One way ticket - Eruption.mp3`,
            songImg: `assets/img/70/One way ticket - Eruption.jpg`,
            en: `The track was originally performed by Neil Sedaka and included as the B-side on Sedaka's 1959 single "Oh! Carol". In 1961, the song featured in the track listing of his third studio album, Neil Sedaka Sings Little Devil and His Other Hits, but was never released as a standalone single. Despite this, the song made it to number one on the Japanese pop charts, where it was affectionately called "The Choo-Choo Train Song".`,
            ru: `One Way Ticket (с англ. — «Билет в один конец») — песня группы «Eruption» из альбома Leave a Light (1978). В России и странах бывшего СССР известна также как «Синий иней» или «Синяя песня». В 1968 году поэт Альберт Азизов написал русский текст. Он не имел ничего общего с английским оригиналом и назывался «Синяя песня» (или, по первым словам «Синий, синий иней…»).`,
        }, 
        {
            songName: `Rasputin - Boney M.`,
            songSrc: `assets/music/70/cut/Rasputin - Boney M..mp3`,
            songImg: `assets/img/70/Rasputin - Boney M..jpg`,
            en: `"Rasputin" - written by the group's creator Frank Farian, along with George Reyam and Fred Jay, it is a song about Grigori Rasputin, a friend and advisor of Tsar Nicholas II of Russia and his family during the early 20th century. The song describes Rasputin as a playboy, mystical healer, and political manipulator.`,
            ru: `«Rasputin» — в песне идёт речь о Григории Распутине, неприязни некоторых людей высшего общества к нему, а также о его смерти. Песня описывает Распутина как плейбоя, мистического целителя и политического манипулятора.`,
        }, 
        {
            songName: `Stayin' Alive - Bee Gees`,
            songSrc: `assets/music/70/cut/Stayin' Alive - Bee Gees.mp3`,
            songImg: `assets/img/70/Stayin' Alive - Bee Gees.jpg`,
            en: `"Stayin' Alive" is a song written and performed by the Bee Gees from the Saturday Night Fever motion picture soundtrack. The song was released in 1977 as the second single from the Saturday Night Fever soundtrack. The band co-produced the song with Albhy Galuten and Karl Richardson. It is one of the Bee Gees' signature songs. In 2004, "Stayin' Alive" was placed at No. 189 on the list of Rolling Stone's 500 Greatest Songs of All Time. The 2021 updated Rolling Stone list of 500 Greatest Songs placed "Stayin' Alive" at No. 99.`,
            ru: `«Stayin’ Alive» (с англ. — «Оставаться в живых») — песня британской поп-группы Bee Gees, написанная для культового диско-фильма «Лихорадка субботнего вечера». После релиза сразу же попала в чарты и во многих заняла первое место. Например, в Billboard Hot 100, начиная с 4 февраля 1978 года, удерживала лидирующую позицию в течение четырёх недель. Композиция является самой узнаваемой по сравнению с другими песнями фильма и имеет в истории группы определяющую роль.`,
        }, 
    ],
    [
        {
            songName: `Brother Louie - Modern Talking`,
            songSrc: `assets/music/80/cut/Brother Louie - Modern Talking.mp3`,
            songImg: `assets/img/80/Brother Louie - Modern Talking.jpg`,
            en: `"Brother Louie" was released on 27 January 1986 and it reached No. 1 on 3 March 1986 in Germany. The single spent four weeks at the top and total of 17 weeks on the German chart. In the United Kingdom, it peaked at No. 4 in the charts and went silver for shipments in excess of 250,000 units. "Brother Louie" was also certified silver in France for selling over 250,000 units. It is believed that the song was written by Dieter Bohlen about producer Luis Rodríguez, as he was a close associate of Bohlen and worked on many of the Modern Talking songs.`,
            ru: `"Brother Louie" был выпущен 27 января 1986 г. и 3 марта 1986 г. занял первое место в Германии. Сингл провел четыре недели на вершине и в общей сложности 17 недель в немецком чарте. В Соединенном Королевстве он занял 4-е место в чартах и стал серебряным при отгрузке более 250 000 единиц. "Brother Louie" также получил серебряный сертификат во Франции за продажу более 250 000 копий. Считается, что песня была написана Дитером Боленом о продюсере Луисе Родригесе, поскольку он был близким соратником Болена и работал над многими песнями Modern Talking.`,
        }, 
        {
            songName: `Casino - Passengers`,
            songSrc: `assets/music/80/cut/Casino - Passengers.mp3`,
            songImg: `assets/img/80/Casino - Passengers.jpg`,
            en: `On March 3, 1981, "Casino" was released - the lead single of the third studio album "Casino" by the Italian pop quartet Passengers. The song did not enter any chart, including the Italian one, however, for some reason it was very popular in the USSR.`,
            ru: `3 марта 1981 года вышел "Casino" - лид-синнгл третьего студийного альбома "Casino" итальянского поп-квартета Passengers. Песня не вошла ни в один чарт, включая итальянский, однако, почему-то была очень популярна в СССР.`,
        }, 
        {
            songName: `Cause You Are Young - C.C. Catch`,
            songSrc: `assets/music/80/cut/Cause You Are Young - C.C. Catch.mp3`,
            songImg: `assets/img/80/Cause You Are Young - C.C. Catch.jpg`,
            en: `Caroline Katarina Müller, better known as C.C. Ketch or C.C. Catch, is a Dutch-born German singer. Performs songs in English in pop and disco styles. She has lived in London since 2007.`,
            ru: `Кароли́на Катари́на Мю́ллер, более известная как Си Си Кетч или Си Си Кэтч (англ. C. C. Catch), — немецкая певица нидерландского происхождения. Исполняет песни на английском языке в стилях поп и диско. С 2007 года проживала в Лондоне.`,
        }, 
        {
            songName: `Cheri Cheri Lady - Modern Talking`,
            songSrc: `assets/music/80/cut/Cheri Cheri Lady - Modern Talking.mp3`,
            songImg: `assets/img/80/Cheri Cheri Lady - Modern Talking.jpg`,
            en: `"Cheri, Cheri Lady" is the only single released from Modern Talking's second album Let's Talk About Love, and it was the third single in a row that peaked at number one on the German singles chart, after "You're My Heart, You're My Soul" and "You Can Win If You Want". "Cheri, Cheri Lady" was released on 2 September 1985, but peaked at No. 1 in Germany on 14 October 1985.`,
            ru: `«Cheri, Cheri Lady» — песня немецкой диско-группы Modern Talking. Она дважды выходила синглом — в 1985 и 1998 годах. Слова и музыку написал Дитер Болен. Это единственный сингл со второго альбома Modern Talking Let’s Talk About Love, и это был третий сингл подряд после «You’re My Heart, You’re My Soul» и «You Can Win If You Want», который достиг первой строчки в немецком чарте. «Cheri, Cheri Lady» был выпущен 2 сентября 1985 года и достиг № 1 в Германии 14 октября 1985 года.`,
        }, 
        {
            songName: `Eye of the Tiger - Survivor`,
            songSrc: `assets/music/80/cut/Eye of the Tiger - Survivor.mp3`,
            songImg: `assets/img/80/Eye of the Tiger - Survivor.jpg`,
            en: `The song was written at the request of Sylvester Stallone for the film "Rocky 3". Topped the Billboard Hot 100 on July 24, 1982 and stayed there for six weeks; twenty-third on Billboard's All Time Top 100 and sixty-third on VH1's list of the top hard rock songs of all time. Survivor released a repackage of the song in 2007.`,
            ru: `Песня была написана по просьбе Сильвестра Сталлоне для фильма «Рокки 3». Заняла вершину Billboard Hot 100 24 июля 1982 года и оставалась на ней в течение шести недель; двадцать третья песня в списке Billboard’s All Time Top 100 и шестьдесят третья в списке лучших хард-рок композиций всех времен по версии VH1. В 2007 году группа Survivor выпустила переиздание песни.`,
        }, 
        {
            songName: `Flash In The Night - Secret Service`,
            songSrc: `assets/music/80/cut/Flash In The Night - Secret Service.mp3`,
            songImg: `assets/img/80/Flash In The Night - Secret Service.jpg`,
            en: `Secret Service (from English - "Secret Service") is a Swedish musical group that performed their works in the genre of popular music in the 1980s. The composition of the group has changed over time, its constant members are keyboardist Ulf Wahlberg and Tim Norell, the latter is the author of the vast majority of Secret Service's songs.`,
            ru: `«Secret Service» (с англ. — «Тайная служба») — шведская музыкальная группа, исполнявших свои произведения в жанре популярной музыки в 1980-х годах. Состав группы в разное время менялся, неизменными её участниками являются клавишник Ульф Вальберг и Тим Норелл, последний является автором подавляющего большинства песен группы Secret Service.`,
        }, 
        {
            songName: `Gelato Al Cioccolato - Pupo`,
            songSrc: `assets/music/80/cut/Gelato Al Cioccolato - Pupo.mp3`,
            songImg: `assets/img/80/Gelato Al Cioccolato - Pupo.jpg`,
            en: `Gelato al cioccolato is the second studio album by the Italian singer Pupo, released in 1979. About the title track, a seemingly light and easy-going song, years later Pupo revealed that in reality this hides a heavy sexual allusion because it does reference to a passionate adventure had by the author of the text, Cristiano Malgioglio, in North Africa with a local boy.`,
            ru: `Gelato al cioccolato — второй студийный альбом итальянского певца Пупо, выпущенный в 1979 году. Что касается заглавного трека, казалось бы, легкой и беззаботной песни, годы спустя Пупо рассказал, что на самом деле за ним скрывается тяжелый сексуальный намек, поскольку он действительно отсылает к страстное приключение автора текста Криштиану Мальджольо в Северной Африке с местным мальчиком.`,
        }, 
        {
            songName: `Ghostbusters - Ray Parker Jr.`,
            songSrc: `assets/music/80/cut/Ghostbusters - Ray Parker Jr..mp3`,
            songImg: `assets/img/80/Ghostbusters - Ray Parker Jr..jpg`,
            en: `"Ghostbusters" is a song written by Ray Parker Jr. as the theme to the film of the same name, and included on the film's soundtrack. Debuting at number 68 on June 16, 1984, the song peaked at number one on the Billboard Hot 100 on August 11, staying there for three weeks, (Parker Jr.'s only number one on that chart), and at number two on the UK Singles Chart on September 16, staying there for three weeks.`,
            ru: `«Охотники за привидениями» — песня, написанная Рэем Паркером-младшим в качестве темы к одноименному фильму и включенная в саундтрек к фильму. Дебютировав под номером 68 16 июня 1984 года, песня достигла пика под номером один в Billboard Hot 100 11 августа, оставаясь там в течение трех недель (единственный номер один у Паркера-младшего в этом чарте), и под номером два в чарте. UK Singles Chart 16 сентября, оставаясь там на три недели.`,
        }, 
        {
            songName: `Heaven and Hell - C.C. Catch`,
            songSrc: `assets/music/80/cut/Heaven and Hell - C.C. Catch.mp3`,
            songImg: `assets/img/80/Heaven and Hell - C.C. Catch.jpg`,
            en: `In the USSR in 1987, in the New Year's program "Rhythms of the Planet", a performance by C.C. Catch, with the song "Heaven and hell"`,
            ru: `В СССР в 1987 в новогодней программе «Ритмы планеты» показали выступление C.C. Catch,  с песней «Heaven and hell»`,
        }, 
        {
            songName: `I Can Lose My Heart Tonight - C.C. Catch`,
            songSrc: `assets/music/80/cut/I Can Lose My Heart Tonight - C.C. Catch.mp3`,
            songImg: `assets/img/80/I Can Lose My Heart Tonight - C.C. Catch.jpg`,
            en: `February 1, 1987 in the USSR in the "Musical Mosaic" included the song "I Can Lose My Heart. It is noteworthy that in all three programs, Soviet announcers did not announce her stage name in full, but only “singer Ketch” or “Ketch sings,`,
            ru: `1 февраля 1987 в СССР в «Музыкальной мозаике» включили песню «I Can Lose My Heart . Примечательно, что во всех трех программах советские дикторы объявляли её сценическое имя не полностью, а лишь «певица Кетч» или «поёт Кетч,`,
        }, 
        {
            songName: `Strangers by Night - C.C. Catch`,
            songSrc: `assets/music/80/cut/Strangers by Night - C.C. Catch.mp3`,
            songImg: `assets/img/80/Strangers by Night - C.C. Catch.jpg`,
            en: `The first appearance of the singer on Soviet television took place on November 9, 1986 in the program "Rhythms of the Planet" C.C. Catch performed the song "Strangers by night"`,
            ru: `Первое появление певицы на советском телевидении состоялось 9 ноября 1986 в программе «Ритмы планеты» C.C.Catch исполнила песню «Strangers by night»`,
        },
        {
            songName: `Sunny - Boney M.`,
            songSrc: `assets/music/80/cut/Sunny - Boney M..mp3`,
            songImg: `assets/img/80/Sunny - Boney M..jpg`,
            en: `Boney M. were among the foreign performers officially "permitted" in the USSR (although, from time to time, they were included in various banned lists, for example, because of the song "Rasputin"). Some of the group's compositions, such as Sunny (1976), were released in the USSR on records by the Melodiya company (later, already in Russia, all albums and compilations were successfully sold). The songs of the group were sometimes broadcast on the radio, and videos were occasionally shown on Central Television in the programs “Melodies and rhythms of foreign pop music”, “Morning mail”, etc.`,
            ru: `Boney M. были в числе официально «разрешённых» в СССР зарубежных исполнителей (хотя, время от времени, и они включались в различные запретные списки, например из-за песни «Rasputin»). Некоторые композиции группы, например Sunny (1976), выпускались в СССР на пластинках фирмой «Мелодия» (позже, уже в России, успешно продавались все альбомы и компиляции). Песни группы иногда транслировались по радио, а видеозаписи изредка демонстрировались по Центральному телевидению в передачах «Мелодии и ритмы зарубежной эстрады», «Утренняя почта» и др.`,
        }, 
        {
            songName: `The Lady In Red - Chris De Burgh`,
            songSrc: `assets/music/80/cut/The Lady In Red - Chris De Burgh.mp3`,
            songImg: `assets/img/80/The Lady In Red - Chris De Burgh.jpg`,
            en: `The song was written by de Burgh about his wife Diana, although it is not explicitly stated in the song, and was released as part of the Into the Light album. In the documentary series This Is Your Life, de Burgh stated that the song was inspired by the memory of the first time he saw Diana and the thought that men often cannot even remember what their wives were wearing when they first met. The final words of the song are a declaration of love.`,
            ru: `Песня была написана де Бургом о его жене Диане, хотя в песне об этом прямо не указывается, и была выпущена в составе альбома Into the Light. В документальном сериале This Is Your Liferuen де Бург заявил, что песня была вдохновлена памятью о том, как он впервые увидел Диану и мыслями о том, что мужчины зачастую не могут даже вспомнить, во что их жёны были одеты в момент первой встречи. Финальные слова песни — признание в любви.`,
        }, 
        {
            songName: `Touch By Touch - Joy`,
            songSrc: `assets/music/80/cut/Touch By Touch - Joy.mp3`,
            songImg: `assets/img/80/Touch By Touch - Joy.jpg`,
            en: `"Touch by Touch" is a song by Austrian Euro disco band Joy, released in 1985 as the second single from their debut album, Hello. The song was a huge success in their homeland, where it reached number one. In Germany, the song reached the top 20, peaking at No. 18 in 1986. It also became a hit in East Asia and the Philippines, and remains as the band's signature song.`,
            ru: `«Touch by Touch» — песня австрийской евродиско-группы Joy, выпущенная в 1985 году как второй сингл с их дебютного альбома Hello. Песня имела огромный успех у них на родине, где заняла первое место. В Германии песня вошла в топ-20, заняв 18-е место в 1986 году. Она также стала хитом в Восточной Азии и на Филиппинах и остается фирменной песней группы.`,
        },  
        {
            songName: `Words - F.R. David`,
            songSrc: `assets/music/80/cut/Words - F.R. David.mp3`,
            songImg: `assets/img/80/Words - F.R. David.jpg`,
            en: `"Words" is a song by F. R. David, released as a single in 1982 from his debut album of the same name. The song was a huge European hit, peaking at number one in Germany, Switzerland, Sweden, Austria and Norway. In the spring of 1983, it peaked at number two on the British charts. `,
            ru: `«Words» — песня Ф. Р. Дэвида, выпущенная как сингл в 1982 году с его одноименного дебютного альбома. Песня стала огромным европейским хитом, заняв первое место в Германии, Швейцарии, Швеции, Австрии и Норвегии. Весной 1983 года он занял второе место в британских чартах.`,
        }, 
        {
            songName: `You Can Win If You Want - Modern Talking`,
            songSrc: `assets/music/80/cut/You Can Win If You Want - Modern Talking.mp3`,
            songImg: `assets/img/80/You Can Win If You Want - Modern Talking.jpg`,
            en: `"You Can Win If You Want" is the second song by German disco group Modern Talking, released in March 1985, from their debut album The First Album. After spending three weeks in the top 5, the song reached the top of the charts, eventually reaching sales of over 250,000 units in Germany alone and therefore going gold. The single also reached number eight on the charts in France and was sold in gold (500,000 units).`,
            ru: `«You Can Win If You Want» (с англ. — «Ты сможешь победить, если захочешь») — вторая песня немецкой диско-группы Modern Talking, выпущенная в марте 1985 года, с их дебютного альбома The First Album.
            После трёх недель нахождения в топ-5, песня достигла вершин хит-парадов, в конечном итоге сингл достиг продаж более чем 250 000 единиц в одной только Германии и поэтому стал золотым. Также сингл достиг восьмого места в хит-параде во Франции и продан золотым тиражом (500 000 единиц).`,
        }, 
        {
            songName: `You Spin Me Round - Dead Or Alive`,
            songSrc: `assets/music/80/cut/You Spin Me Round - Dead Or Alive.mp3`,
            songImg: `assets/img/80/You Spin Me Round - Dead Or Alive.jpg`,
            en: `You Spin Me Round (Like a Record)" is a song by English pop band Dead or Alive, featured on their second album, Youthquake (1985). Released as a single in November 1984, it reached No. 1 in the UK in March 1985, taking 17 weeks to get there. It was the first UK number-one hit by the Stock Aitken Waterman production trio. On the U.S. Billboard Hot 100, it peaked at No. 11 on 17 August of that year.`,
            ru: `You Spin Me Round — песня английской поп-группы Dead or Alive, вошедшая в их второй альбом Youthquake (1985). Выпущенная как сингл в ноябре 1984 года, в марте она заняла первое место в Великобритании. 1985 г., чтобы добраться туда, потребовалось 17 недель. Это был первый хит номер один в Великобритании продюсерского трио Stock Aitken Waterman.`,
        }, 
    ],
    [
        {
            songName: `All That She Wants - Ace of Base`,
            songSrc: `assets/music/90/cut/All That She Wants - Ace of Base.mp3`,
            songImg: `assets/img/90/All That She Wants - Ace of Base.jpg`,
            en: `"All That She Wants" is a song by the Swedish musical group Ace of Base. It was released as the band's second single from their debut studio album Happy Nation. In early 1993, the song reached number one on the charts in many countries including Denmark, Germany, Italy, Spain, the UK and Australia. In the US, the single peaked at number 2 on the Billboard Hot 100. It was certified platinum.`,
            ru: `«All That She Wants»  — песня шведской музыкальной группы Ace of Base. Была издана как второй сингл группы с их дебютного студийного альбома Happy Nation. В начале 1993 года песня достигла первого места в чартах многих стран, включая Данию, Германию, Италию, Испанию, Великобританию и Австралию. В США сингл занял 2-е место в чарте Billboard Hot 100. Он был сертифицирован платиновым.`,
        }, 
        {
            songName: `Blue - Eiffel 65`,
            songSrc: `assets/music/90/cut/Blue - Eiffel 65.mp3`,
            songImg: `assets/img/90/Blue - Eiffel 65.jpg`,
            en: `"Blue (Da Ba Dee)" is a song by the Italian music group Eiffel 65. The lyrics are a play on words: it describes a character who lives in a blue world and experiences "blue" (sad) feelings.`,
            ru: `«Blue (Da Ba Dee)» — песня итальянской музыкальной группы Eiffel 65. Текст представляет собой игру слов: он описывает героя, который живёт в синем мире и испытывает «синие» (печальные) чувства.`,
        },
        {
            songName: `Coco Jamboo - Mr.Presidenеt`,
            songSrc: `assets/music/90/cut/Coco Jamboo - Mr.Presidenеt.mp3`,
            songImg: `assets/img/90/Coco Jamboo - Mr.Presidenеt.jpg`,
            en: `The name of the group stands for: "M" and "R" - short for "music" and "rhythm", respectively; "president" (Russian President) - the most that a person can achieve within society. The group's most famous song is "Coco Jamboo".`,
            ru: `Название группы расшифровывается так: «M» и «R» — сокращения от «music» и «rhythm» соответственно; «president» (рус. президент) — наибольшее, чего может добиться человек в рамках общества. Самая известная композиция группы — «Coco Jamboo».`,
        },
        {
            songName: `Everybody - Backstreet Boys`,
            songSrc: `assets/music/90/cut/Everybody - Backstreet Boys.mp3`,
            songImg: `assets/img/90/Everybody - Backstreet Boys.jpg`,
            en: `The record company's management decided that the title of the song, which refers to the band's "comeback" with the second album, was inappropriate for the band's first US album. After the song's release as a single in Europe, "Everybody" became popular in Canada. American radio stations along the border also aired the song. The band met with the label's management and asked for the song to be included on the album after several million copies of the album had been produced.`,
            ru: `Руководство звукозаписывающей компании решило, что название песни, которое ссылается на «возвращение» группы со вторым альбомом, не подходит для первого альбома группы в США. После выпуска песни синглом в Европе, «Everybody» стала популярна в Канаде. Американские радиостанции, расположенные вдоль границы также поставили песню в эфир. Группа встретилась с руководством лейбла и попросила включить песню в альбом уже после того как были произведены несколько миллионов экземпляров альбома`,
        },
        {
            songName: `Macarena - Los Del Rio`,
            songSrc: `assets/music/90/cut/Macarena - Los Del Rio.mp3`,
            songImg: `assets/img/90/Macarena - Los Del Rio.jpg`,
            en: `The song was recorded in 1992 and released in 1993 as a rumba. Reached considerable popularity in Spain, Colombia and Mexico. It also became popular in Puerto Rico due to its use as an unofficial campaign theme song for Governor Pedro Rossello. Being the base for many cruise ships, Puerto Rico is visited by a large number of tourists. All of them constantly heard the song "Macarena" during their stay on the island. This may explain how the song spread and became a hit in cities with significant Hispanic communities in the United States, particularly Miami and New York.`,
            ru: `Песня была записана в 1992 году, и выпущена в 1993 году как румба. Достигла значительной популярности в Испании, Колумбии и Мексике. Она также стала популярной в Пуэрто-Рико из-за её использования в качестве неофициальной музыкальной темы для предвыборной кампании губернатора Педро Росселло. Являясь базой для многих круизных судов, Пуэрто-Рико посещается большим числом туристов. Все они постоянно слышали песню «Макарена» во время своего пребывания на острове. Это может объяснить как песня распространилась и стала хитом в городах со значительным числом латиноамериканских общин в Соединённых Штатах, в частности Майами и Нью-Йорке.`,
        },
        {
            songName: `Pump Up The Jam - Technotronic`,
            songSrc: `assets/music/90/cut/Pump Up The Jam - Technotronic.mp3`,
            songImg: `assets/img/90/Pump Up The Jam - Technotronic.jpg`,
            en: `Pump Up the Jam" is the opening track on Belgian act Technotronic's first album, Pump Up the Jam: The Album (1989). It was released as a single on 18 August 1989 and was a worldwide hit, reaching number two in the United Kingdom `,
            ru: `Pump Up the Jam" - это вступительный трек на первом альбоме бельгийской группы Technotronic, Pump Up the Jam: The Album (1989). Он был выпущен как сингл 18 августа 1989 года и стал мировым хитом, заняв второе место в Великобритании.`,
        },
        {
            songName: `Rhythm Is a Dancer - Forfour Seasons`,
            songSrc: `assets/music/90/cut/Rhythm Is a Dancer - Forfour Seasons.mp3`,
            songImg: `assets/img/90/Rhythm Is a Dancer - Forfour Seasons.jpg`,
            en: `"Rhythm Is a Dancer" was originally not planned to be released as a single. Good club reactions to the track made Snap!'s German label, Logic, change their minds. Logic arranged a private test at its own discotheque, the Omen, to see how well the public responded to the new song. That's where the instant club appeal of "Rhythm Is a Dancer" first came to notice. `,
            ru: `"Rhythm Is a Dancer" изначально не планировалось выпускать как сингл. Хорошая реакция клубов на трек заставила немецкий лейбл Snap!, Logic, изменить свое мнение. Logic устроила закрытый тест на собственной дискотеке Omen, чтобы узнать, насколько хорошо публика отреагирует на новую песню. Именно здесь впервые обратили внимание на мгновенную клубную привлекательность "Rhythm Is a Dancer".`,
        },
        {
            songName: `Scatman - George Price`,
            songSrc: `assets/music/90/cut/Scatman - George Price.mp3`,
            songImg: `assets/img/90/Scatman - George Price.jpg`,
            en: `Starting a new chapter in his career, the singer was worried that by listening to his songs, people would understand that he had a stutter, so he followed his wife's advice and directly stated this in the text. Another reason for creating the song was the singer's desire to help children with stuttering overcome this disease and not let stuttering prevent them from living a full life. The dance beat and singing combined with the scat eventually formed Scatman's style.`,
            ru: `Начиная новую главу в своей карьере, певец переживал, что, слушая его песни, люди поймут, что он страдает заиканием, поэтому он последовал совету жены и прямо сказал об этом в тексте. Еще одной причиной создания песни было желание певца помочь детям, страдающим заиканием, перебороть эту болезнь и не позволить заиканию мешать им жить полноценно. Танцевальный бит и пение в сочетании со скэтом в итоге сформировали стиль Скэтмэна.`,
        },
    ],
    [
        {
            songName: `Buttons - The Pussycat Dolls`,
            songSrc: `assets/music/00/cut/Buttons - The Pussycat Dolls.mp3`,
            songImg: `assets/img/00/Buttons - The Pussycat Dolls.jpg`,
            en: `It is a hip hop-influenced pop and R&B track featuring synthesizers and a Middle Eastern rhythm, with the group pleading a reluctant man to help them undress whilst adopting a submissive stance. A remix version featuring American rapper Snoop Dogg was released as the album's fourth single on April 11, 2006, by A&M Records and Interscope Records.`,
            ru: `Это поп- и R&B-трек с элементами хип-хопа, в котором используются синтезаторы и ближневосточный ритм, а группа умоляет сопротивляющегося мужчину помочь им раздеться, при этом принимая покорную позу. Версия ремикса с участием американского рэпера Снуп Догга была выпущена в качестве четвертого сингла альбома 11 апреля 2006 года на лейблах A&M Records и Interscope Records.`,
        }, 
        {
            songName: `Feel Good Inc. - Gorillaz`,
            songSrc: `assets/music/00/cut/Feel Good Inc. - Gorillaz.mp3`,
            songImg: `assets/img/00/Feel Good Inc. - Gorillaz.jpg`,
            en: `"Feel Good Inc." is a song by British virtual band Gorillaz featuring American hip-hop group De La Soul. The song was released as the lead single from the band's second studio album, Demon Days, on 9 May 2005, preceding the release of the album by two days. `,
            ru: `"Чувствовать себя хорошо Inc." — песня британской виртуальной группы Gorillaz при участии американской хип-хоп группы De La Soul. Песня была выпущена в качестве ведущего сингла со второго студийного альбома группы Demon Days 9 мая 2005 года, за два дня до выхода альбома.`,
        }, 
        {
            songName: `First Day - Timo Maas feat. Brian Molko`,
            songSrc: `assets/music/00/cut/First Day - Timo Maas feat. Brian Molko.mp3`,
            songImg: `assets/img/00/First Day - Timo Maas feat. Brian Molko.jpg`,
            en: `Timo Maas (born July 27, 1969, Bückeburg, West Germany) is a German DJ/producer and remixer[1] whose career in electronic music spans well over 30 years. His remix of Azzido Da Bass's single "Dooms Night" helped launch his career in 2000.`,
            ru: `Тимо Маас (родился 27 июля 1969 года, Бюкебург, Западная Германия) — немецкий ди-джей, продюсер и ремиксер[1], чья карьера в области электронной музыки насчитывает более 30 лет. Его ремикс на сингл Azzido Da Bass "Dooms Night" помог начать его карьеру в 2000 году.`,
        }, 
        {
            songName: `In the Shadows - The Rasmus`,
            songSrc: `assets/music/00/cut/In the Shadows - The Rasmus.mp3`,
            songImg: `assets/img/00/In the Shadows - The Rasmus.jpg`,
            en: `The song's chorus is based on a technique known as the "millennial whoop", which has since become fashionable and is still used frequently in popular music to this day.`,
            ru: `Припев песни основан на приёме, получившем название «millennial whoop», который после этого вошёл в моду и по сей день часто используется в популярной музыке`,
        }, 
        {
            songName: `Oops! I Did It Again - Britney Spears`,
            songSrc: `assets/music/00/cut/Oops! I Did It Again - Britney Spears.mp3`,
            songImg: `assets/img/00/Oops! I Did It Again - Britney Spears.jpg`,
            en: `The lyrics refer to a woman who views love as a game, and she decides to use that to her advantage by playing with the emotions of a boy who likes her. Its bridge features spoken dialogue which references the hit 1997 film Titanic.`,
            ru: `В тексте говорится о женщине, которая рассматривает любовь как игру, и она решает использовать это в своих интересах, играя с эмоциями мальчика, который ей нравится. На мостике можно услышать диалоги, отсылающие к популярному фильму 1997 года «Титаник».`,
        }, 
        {
            songName: `Relax, Take It Easy - MIKA`,
            songSrc: `assets/music/00/cut/Relax, Take It Easy - MIKA.mp3`,
            songImg: `assets/img/00/Relax, Take It Easy - MIKA.jpg`,
            en: `In the UK, it failed to chart upon its original release, but after "Grace Kelly" topped the charts in January 2007, it managed to peak at number 67 on the UK Downloads Chart because of download sales.`,
            ru: `В Великобритании он не попал в чарты после своего первоначального выпуска, но после того, как "Grace Kelly" возглавил чарты в январе 2007 года, ему удалось занять 67-е место в британском чарте загрузок из-за продаж загрузок.`,
        }, 
        {
            songName: `Stronger - Kanye West`,
            songSrc: `assets/music/00/cut/Stronger - Kanye West.mp3`,
            songImg: `assets/img/00/Stronger - Kanye West.jpg`,
            en: `The cover features West's symbol, a teddy bear, and the same glasses as Kanye's in the video. West performed a partial version of this song on July 1, 2007, at a tribute concert for Princess Diana at Wembley Stadium. 63,000 people were in the stadium, and approximately 500 million in more than 140 countries watched the event on TV.`,
            ru: `На обложке изображён символ Уэста — плюшевый мишка, на котором надеты такие же очки как у Канье в клипе. Уэст исполнил частичную версию этой песни 1 июля 2007 года, на концерте в честь Принцессы Дианы на стадионе Уэмбли. 63 000 человек были на стадионе, а примерно 500 миллионов в более чем 140 странах — смотрели это мероприятие по телевизору.`,
        }, 
        {
            songName: `The magic key  - One T + Cool T`,
            songSrc: `assets/music/00/cut/The magic key  - One T + Cool T.mp3`,
            songImg: `assets/img/00/The magic key  - One T + Cool T.jpg`,
            en: ` To date, it remains One-T's most successful single. An animated music video was also released, featuring the characters on the single cover.`,
            ru: `На сегодняшний день он остается самым успешным синглом One-T. Также был выпущен анимационный видеоклип с участием персонажей обложки сингла.`,
        }

    ], 
    [
        {
            songName: `Alejandro - Lady GaGa`,
            songSrc: `assets/music/10/cut/Alejandro - Lady GaGa.mp3`,
            songImg: `assets/img/10/Alejandro - Lady GaGa.jpg`,
            en: `The song was inspired by Gaga's fear of men and is about her bidding farewell to her Latino lovers named Alejandro, Roberto and Fernando.`,
            ru: `Песня была вдохновлена страхом Гаги перед мужчинами и повествует о том, как она прощается со своими латиноамериканскими любовниками по имени Алехандро, Роберто и Фернандо.`,
        }, 
        {
            songName: `Hot'N'Cold -Katy Perry`,
            songSrc: `assets/music/10/cut/Hot'N'Cold -Katy Perry.mp3`,
            songImg: `assets/img/10/Hot'N'Cold -Katy Perry.jpg`,
            en: `In April 2007, Perry signed a record deal with Capitol Records. She became widely known around the world after the release of the single "I Kissed a Girl" and the album One of the Boys in 2008. The subsequent singles "Hot n Cold" and "Waking Up in Vegas" also enjoyed wide international popularity.`,
            ru: `В апреле 2007 года Перри подписала контракт со звукозаписывающей компанией Capitol Records. Она стала широко известна во всем мире после выхода сингла «I Kissed a Girl» и альбома One of the Boys в 2008 году. Последующие синглы «Hot n Cold» и «Waking Up in Vegas» также пользовались широкой международной популярностью. `,
        }, 
        {
            songName: `In And Out Of Love - Armin van Buuren ft. Sharon den Adel`,
            songSrc: `assets/music/10/cut/In And Out Of Love - Armin van Buuren ft. Sharon den Adel.mp3`,
            songImg: `assets/img/10/In And Out Of Love - Armin van Buuren ft. Sharon den Adel.jpg`,
            en: `"In and Out of Love" is a collaboration between Dutch DJ and record producer Armin van Buuren and Dutch singer and songwriter Sharon den Adel from the band Within Temptation. It was released on 6 August 2008 as the second single from van Buuren's third studio album, Imagine.`,
            ru: `«In and Out of Love» — совместный проект голландского диджея и продюсера Армина ван Бюрена и голландской певицы и автора песен Шарон ден Адель из группы Within Temptation. Он был выпущен 6 августа 2008 года как второй сингл с третьего студийного альбома ван Бюрена Imagine.`,
        }, 
        {
            songName: `Levels - Avicii`,
            songSrc: `assets/music/10/cut/Levels - Avicii.mp3`,
            songImg: `assets/img/10/Levels - Avicii.jpg`,
            en: `"Levels" is a progressive house song by Swedish DJ Avicii that was released on 28 October 2011 through Universal Music Group on iTunes. "Levels" topped the Swedish Singles Chart. `,
            ru: `«Levels» — прогрессивная хаус-песня шведского диджея Avicii, выпущенная 28 октября 2011 года на лейбле Universal Music Group в iTunes. "Levels" возглавил шведский чарт синглов.`,
        }, 
        {
            songName: `Meet Me Halfway - Black Eyed Peas`,
            songSrc: `assets/music/10/cut/Meet Me Halfway - Black Eyed Peas.mp3`,
            songImg: `assets/img/10/Meet Me Halfway - Black Eyed Peas.jpg`,
            en: `It is a dance-pop song that combines futuristic electro hop beats with vintage 1980s pop stylings and a sampled intro of "Maps" by Yeah Yeah Yeahs.`,
            ru: `Это танцевальная поп-песня, в которой футуристические ритмы электро-хопа сочетаются с винтажным стилем поп-музыки 1980-х и семплированным вступлением «Maps» группы Yeah Yeah Yeahs.`,
        }, 
        {
            songName: `Mr. Saxobeat - Alexandra Stan`,
            songSrc: `assets/music/10/cut/Mr. Saxobeat - Alexandra Stan.mp3`,
            songImg: `assets/img/10/Mr. Saxobeat - Alexandra Stan.jpg`,
            en: `The song was a great success in the singer's home country of Romania, where she reached number one for eight consecutive weeks, and became the longest-running song in Romania in 2010.`,
            ru: `Песня имела большой успех на родине певицы — в Румынии, где она достигла первого места, и находится там восемь недель подряд, и стала лидером по продолжительности нахождения на этой позиции в Румынии в 2010 году.`,
        }, 
        {
            songName: `Sexy Chick - David_Guetta Feat. Akon`,
            songSrc: `assets/music/10/cut/Sexy Chick - David_Guetta Feat. Akon.mp3`,
            songImg: `assets/img/10/Sexy Chick - David_Guetta Feat. Akon.jpg`,
            en: `Pierre David Guetta is a French DJ and music producer. He has over 10 million albums and 65 million singles sales globally, with more than 10 billion streams.
            Pierre David Guetta is a French DJ and music producer. He has over 10 million albums and 65 million singles sales globally, with more than 10 billion streams.`,
            ru: `Пьер Давид Гетта — французский диджей и музыкальный продюсер. У него более 10 миллионов альбомов и 65 миллионов продаж синглов по всему миру, более 10 миллиардов прослушиваний.`,
        }
    ]
]


const yearsArr = [`60`, `70`, `80`, `90`, `00`, `10`];